# Validation tests for the uncertainty-quantification algorithms in algorithms/uq/. Checks
# `rollout_steps`/`rollout_chunk_errors` against a hand-rolled explicit-Euler simulation of a
# `polynomial_model_AC` (zero error when the "true" trajectories are generated by the SAME
# model, growing error once the model is perturbed, and correctly zero once more for a DRIVEN
# model when a per-step, per-trajectory control `U` is supplied), and confirms `fit_error_gp`/
# `predict_error` recovers a known, noise-free error function of the state (small residual at
# the training points, non-negative predicted variance everywhere).
#
# Copyright (c) 2026 Dirk Hartmann, TU Darmstadt

using Test, Random, Statistics

# --- Include repo files relative to the root (avoids repeated joinpath calls) ---
const ROOT = normpath(@__DIR__, "..", "..")
use(parts...) = Base.include(Main, joinpath(ROOT, parts...))
use("algorithms", "ml", "ml.jl")
use("algorithms", "uq", "uq.jl")

@testset "uncertainty quantification" begin
    u0 = zeros(2)

    @testset "rollout_steps matches a hand-rolled explicit-Euler simulation" begin
        rng = MersenneTwister(1)
        model = polynomial_model_AC(; nin = 2, nctrl = 2, rng = rng)
        x0 = randn(rng, 2)
        δt, L = 0.05, 4
        X = rollout_steps(model, model.params, x0, u0, δt, L)
        @test size(X) == (2, L + 1)
        @test X[:, 1] == x0
        x = x0
        for n in 2:L+1
            x = x .+ δt .* model.rhs(model.params, x, u0)
            @test X[:, n] ≈ x
        end
    end

    @testset "rollout_chunk_errors is zero when truth is generated by the SAME model" begin
        rng = MersenneTwister(2)
        model = polynomial_model_AC(; nin = 2, nctrl = 2, rng = rng)
        δt, T, ntraj, L = 0.05, 41, 3, 5
        X = Array{Float64}(undef, 2, T, ntraj)
        X[:, 1, :] = randn(rng, 2, ntraj)
        for k in 1:ntraj, n in 2:T
            X[:, n, k] = model.predict(model.params, X[:, n-1, k], u0, δt)
        end
        X0, mse = rollout_chunk_errors(model, model.params, X, δt, 1:ntraj; L = L, u = u0)
        @test length(mse) == ntraj * length(1:L:(T - L))
        @test all(m -> m < 1e-20, mse)                   # exact model, exact recovery

        # perturbing the weights must raise the rollout error
        θ_perturbed = model.params .+ 0.5
        _, mse_perturbed = rollout_chunk_errors(model, θ_perturbed, X, δt, 1:ntraj; L = L, u = u0)
        @test mean(mse_perturbed) > mean(mse)
    end

    @testset "rollout_chunk_errors accepts a per-step, per-trajectory control U (driven models)" begin
        rng = MersenneTwister(4)
        model = polynomial_model_AC(; nin = 2, nctrl = 1, rng = rng)
        δt, T, ntraj, L = 0.05, 41, 3, 5
        Ufull = randn(rng, 1, T, ntraj)                  # a different drive per trajectory
        X = Array{Float64}(undef, 2, T, ntraj)
        X[:, 1, :] = randn(rng, 2, ntraj)
        for k in 1:ntraj, n in 2:T
            X[:, n, k] = model.predict(model.params, X[:, n-1, k], Ufull[:, n-1, k], δt)
        end
        _, mse = rollout_chunk_errors(model, model.params, X, δt, 1:ntraj; L = L, U = Ufull)
        @test all(m -> m < 1e-20, mse)                   # exact model, exact recovery under the true drive

        # scoring the SAME trajectories against zero control (ignoring the real drive) must raise the error
        _, mse_undriven = rollout_chunk_errors(model, model.params, X, δt, 1:ntraj; L = L, u = zeros(1))
        @test mean(mse_undriven) > mean(mse)
    end

    @testset "fit_error_gp / predict_error recover a known noise-free error function" begin
        rng = MersenneTwister(3)
        X0 = 4 .* rand(rng, 2, 60) .- 2                   # scattered points in [-2, 2]^2
        mse = vec(sum(abs2, X0; dims = 1))                # e(x) = ‖x‖², noise-free
        gpmodel = fit_error_gp(X0, mse)

        μ, s = predict_error(gpmodel, X0)
        @test all(s .>= 0)
        @test mean(abs2, μ .- mse) < 0.1 * var(mse)       # close recovery at the training points

        μnew, snew = predict_error(gpmodel, reshape([0.3, -0.2], 2, 1))
        @test snew[1] >= 0
        @test μnew[1] ≈ 0.3^2 + 0.2^2 atol = 0.5
    end
end
